version: '3'
services:
  maria_db:
    image: mariadb
    restart: always
    container_name: maria_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MARIADB_DATABASE: test
      MYSQL_USER: riko
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: secret
    networks:
      - node_app_network
    ports:
      - 3301:3306

  app:
    depends_on:
      - maria_db
    build: app
    # volumes:
    #   - .:/usr/scr/app
    image: node_app
    container_name: node-app
    restart: always
    networks:
      - node_app_network
    ports:
      - 3001:3000
    env_file:
      - app/.env
    command: ["npm","run", "start"]
networks:
  node_app_network:  
